package org.fyp.tmssep490be.entities.enums;

public enum QAReportType {
    CLASSROOM_OBSERVATION,
    PHASE_REVIEW,
    CLO_ACHIEVEMENT_ANALYSIS,
    STUDENT_FEEDBACK_ANALYSIS,
    ATTENDANCE_ENGAGEMENT_REVIEW,
    TEACHING_QUALITY_ASSESSMENT
}
